### ISSUE TITLE
role层如何回复信息，谢谢。

### ISSUE THREAD

**Issue by yiippee** [marklion/zinx#1]
你好，感谢你写的zinx，让我对c++处理服务端有了很大的理解，谢谢。
请问一个问题啊，在role层如何回复接收到的信息呢？能给出一个简单实例吗?谢谢。
我的理解是在ZinxTcpData才有fd，在protocol和role都无法获取fd
那是否需要在protocol和role关联着ZinxTcpData呢？还是我哪里理解错了啊？谢谢。

**Comment by marklion** [comment]
框架不强制管理消息和其经过的层次。发送数据时需要根据业务特点获取到prototcol对象或channel对象，然后调用Zinxkernel:zinxkernel_sendout进行发送。获取的方法由程序员自己实现
